import type { ResponsiveSkeletons } from 'react-native-auto-shimmer';

/**
 * Auto-generated by Skeleton Inspector — 2026-04-11
 * Component  : profile
 * Breakpoints: 358dp (1 total)
 * Pieces     : 14 per breakpoint
 *
 * ✅ x/w are percentages — widths scale automatically on any screen.
 *    y/h are dp values measured from the live layout per breakpoint.
 *
 * Usage:
 *   import profileSkeletons from './profile.skeletons';
 *   <Skeleton initialSkeletons={profileSkeletons} loading={loading}>
 *     <YourComponent />
 *   </Skeleton>
 */
const profileSkeletons: ResponsiveSkeletons = {
  breakpoints: {
    358: {
      name: 'profile',
      viewportWidth: 358,
      width: 358,
      height: 325,
      skeletons: [
        // piece 0 — avatar circle
        { x: 38.827, y: 20, w: 22.346, h: 80, r: '50%' },
        // piece 1
        { x: 30.726, y: 108, w: 38.454, h: 24, r: 8 },
        // piece 2 — small element
        { x: 42.086, y: 140, w: 15.829, h: 17, r: 8 },
        // piece 3 — block (button / card section)
        { x: 5.587, y: 165, w: 88.827, h: 40, r: 8 },
        // piece 4 — small element
        { x: 23.929, y: 217, w: 8.752, h: 19, r: 8 },
        // piece 6 — small element
        { x: 40.875, y: 217, w: 12.011, h: 19, r: 8 },
        // piece 8 — small element
        { x: 64.432, y: 217, w: 8.194, h: 19, r: 8 },
        // piece 5 — timestamp / label
        { x: 23.929, y: 238, w: 8.752, h: 14, r: 8 },
        // piece 7 — timestamp / label
        { x: 39.385, y: 238, w: 14.991, h: 14, r: 8 },
        // piece 9 — timestamp / label
        { x: 61.08, y: 238, w: 14.991, h: 14, r: 8 },
        // piece 10 — button container
        { x: 5.587, y: 265, w: 42.737, h: 40, r: '50%', c: true },
        // piece 12 — button container
        { x: 51.676, y: 265, w: 42.737, h: 40, r: '50%', c: true },
        // piece 11 — small element
        { x: 20.857, y: 276, w: 12.197, h: 17, r: 8 },
        // piece 13 — small element
        { x: 64.618, y: 276, w: 16.853, h: 17, r: 8 },
      ],
    },
  },
};

export default profileSkeletons;
