import type { ResponsiveSkeletons } from 'react-native-auto-shimmer';

/**
 * Auto-generated by Skeleton Inspector — 2026-04-08
 * Component : profile
 * Captured  : 408dp wide · 325dp tall · 13 pieces
 *
 * ✅ Pixel-perfect: x/w are percentages so widths scale on any screen.
 *    y/h are exact dp values measured from the live layout.
 *
 * 💡 To improve cross-platform responsiveness:
 *    - Add more breakpoints captured on other device sizes
 *    - Or switch to a SkeletonDescriptor (descriptor prop) for fully
 *      runtime-computed layout that adapts to any container width
 *
 * Usage:
 *   import profileSkeletons from './profile.skeletons';
 *   <Skeleton initialSkeletons={profileSkeletons} loading={loading}>
 *     <YourComponent />
 *   </Skeleton>
 */
const profileSkeletons: ResponsiveSkeletons = {
  breakpoints: {
    408: {
      name: 'profile',
      viewportWidth: 408,
      width: 408,
      height: 325,
      skeletons: [
        // piece 0 — avatar circle
        { x: 40.196, y: 20, w: 19.608, h: 80, r: '50%' },
        // piece 1
        { x: 33.088, y: 108, w: 33.742, h: 24, r: 8 },
        // piece 2 — small element
        { x: 43.056, y: 140, w: 13.889, h: 17, r: 8 },
        // piece 3 — block (button / card section)
        { x: 4.902, y: 165, w: 90.196, h: 40, r: 8 },
        // piece 4 — small element
        { x: 27.124, y: 217, w: 7.68, h: 19, r: 8 },
        // piece 6 — small element
        { x: 41.993, y: 217, w: 10.539, h: 19, r: 8 },
        // piece 8 — small element
        { x: 62.663, y: 217, w: 7.19, h: 19, r: 8 },
        // piece 5 — timestamp / label
        { x: 27.124, y: 238, w: 7.68, h: 14, r: 8 },
        // piece 7 — timestamp / label
        { x: 40.686, y: 238, w: 13.154, h: 14, r: 8 },
        // piece 9 — timestamp / label
        { x: 59.722, y: 238, w: 13.154, h: 14, r: 8 },
        // piece 10 — button container
        { x: 4.902, y: 265, w: 43.627, h: 40, r: '50%', c: true },
        // piece 11 — button container
        { x: 51.471, y: 265, w: 43.627, h: 40, r: '50%', c: true },
        // piece 12 — small element
        { x: 65.85, y: 276, w: 14.788, h: 17, r: 8 },
      ],
    },
  },
};

export default profileSkeletons;
